### ISSUE TITLE
SyntaxError: Unexpected token '.'

### ISSUE THREAD

**Issue by fampla** [eramdam/tweet-forker#1]
Hi,
first, thanks for this. I would really like to get this started.
But I get an Error.
`SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
{"level":"error","message":"Forever detected script exited with code: 1"}
/home/slevin7/Cloud/tweet-forker/src/server.js:131
        if (!fxStatus.tweet?.replying_to_status) {
                            ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)`

and 
`SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
{"level":"error","message":"Forever detected script exited with code: 1"}
/home/slevin7/Cloud/tweet-forker/src/server.js:83
        if (fxStatus.tweet.author.screen_name?.toLowerCase() !==
                                              ^`

The only thing I changed was the port in server.ts. Did I miss anything?

Thanks in advance

**Comment by eramdam** [comment]
You shouldn't have to touch `server.ts` to change the port, specifying a `PORT` variable in your `.env` file should be enough.

**Comment by slevin-7** [comment]
I remove everything and start again. doesn't touch anything, but the .env file.
Still the same Error.
`SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
{"level":"error","message":"Forever detected script exited with code: 1"}
/home/slevin7/Cloud/tweet-forker/src/server.js:83
        if (fxStatus.tweet.author.screen_name?.toLowerCase() !==
                                              ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
{"level":"error","message":"Forever detected script exited with code: 1"}

`

**Comment by eramdam** [comment]
Are you running the right version of Node (it should be 18 per the `.nvmrc` file and the README)? It looks like it's complaining about some syntax it doesn't support.

**Comment by slevin-7** [comment]
in .nvmrc it says v18.7.0.
Funnily enough, I just tried the docker-compose and lo and behold, it works.
I guess I did something wrong with my node installation.

Thanks for the help.

**Comment by eramdam** [comment]
> in .nvmrc it says v18.7.0. Funnily enough, I just tried the docker-compose and lo and behold, it works. I guess I did something wrong with my node installation.
> 
> Thanks for the help.

yeah, the .nvmrc file is there to indicate something like `nvm` _which_ version to use.
